//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessListHistory
    {
        public int ID { get; set; }
        public int AccessListID { get; set; }
        public Nullable<decimal> UserID { get; set; }
        public string Permissions { get; set; }
        public Nullable<int> UserRole { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    }
}
