//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChecklistItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChecklistItem()
        {
            this.ChecklistItemRecords = new HashSet<ChecklistItemRecord>();
        }
    
        public int ID { get; set; }
        public int ChecklistSectionID { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<bool> HasCheckbox { get; set; }
        public string ItemText { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string ResponseText { get; set; }
        public string OptionType1 { get; set; }
        public Nullable<bool> AllowAutoChecking { get; set; }
        public string OptionType2 { get; set; }
        public string OptionType3 { get; set; }
        public string OptionType4 { get; set; }
        public Nullable<bool> HasITDropDown1 { get; set; }
        public string ITDropDownType1 { get; set; }
        public Nullable<bool> HasITDropDown2 { get; set; }
        public string ITDropDownType2 { get; set; }
    
        public virtual ChecklistSection ChecklistSection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChecklistItemRecord> ChecklistItemRecords { get; set; }
    }
}
