//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChecklistItemRecord
    {
        public int ID { get; set; }
        public int ChecklistItemID { get; set; }
        public int ChecklistRecordID { get; set; }
        public Nullable<bool> IsChecked { get; set; }
        public Nullable<bool> IsOption1Selected { get; set; }
        public Nullable<bool> IsOption2Selected { get; set; }
        public Nullable<bool> IsOption3Selected { get; set; }
        public Nullable<bool> IsOption4Selected { get; set; }
        public string Option1Text { get; set; }
        public string Option2Text { get; set; }
        public string Option3Text { get; set; }
        public string Option4Text { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string OptionType1 { get; set; }
        public Nullable<int> ChecklistSectionID { get; set; }
        public string OptionType2 { get; set; }
        public string OptionType3 { get; set; }
        public string OptionType4 { get; set; }
        public string ITDropDownText1 { get; set; }
        public string ITDropDownText2 { get; set; }
    
        public virtual ChecklistItem ChecklistItem { get; set; }
        public virtual ChecklistRecord ChecklistRecord { get; set; }
    }
}
