//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChecklistSection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChecklistSection()
        {
            this.ChecklistItems = new HashSet<ChecklistItem>();
        }
    
        public int ID { get; set; }
        public int ChecklistID { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string SectionLabel { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string OptionName1 { get; set; }
        public string OptionName2 { get; set; }
        public string OptionName3 { get; set; }
        public string OptionName4 { get; set; }
        public Nullable<byte> HTMLHeaderType { get; set; }
        public Nullable<bool> CanCheckAllOption1 { get; set; }
        public Nullable<bool> CanCheckAllOption2 { get; set; }
        public Nullable<bool> CanCheckAllOption3 { get; set; }
        public Nullable<bool> CanCheckAllOption4 { get; set; }
    
        public virtual Checklist Checklist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChecklistItem> ChecklistItems { get; set; }
    }
}
