//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checklist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Checklist()
        {
            this.ChecklistSections = new HashSet<ChecklistSection>();
            this.ChecklistRecords = new HashSet<ChecklistRecord>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string MetaDataTitle1 { get; set; }
        public string MetaDataTitle2 { get; set; }
        public string MetaDataTitle3 { get; set; }
        public string MetaDataTitle4 { get; set; }
        public string MetaDataTitle5 { get; set; }
        public string MetaDataTitle6 { get; set; }
        public Nullable<bool> IsMeta1Searchable { get; set; }
        public Nullable<bool> IsMeta2Searchable { get; set; }
        public Nullable<bool> IsMeta3Searchable { get; set; }
        public Nullable<bool> IsMeta4Searchable { get; set; }
        public Nullable<bool> IsMeta5Searchable { get; set; }
        public Nullable<bool> IsMeta6Searchable { get; set; }
        public Nullable<bool> IsMeta1Required { get; set; }
        public Nullable<bool> IsMeta2Required { get; set; }
        public Nullable<bool> IsMeta3Required { get; set; }
        public Nullable<bool> IsMeta4Required { get; set; }
        public Nullable<bool> IsMeta5Required { get; set; }
        public Nullable<bool> IsMeta6Required { get; set; }
        public string MetaDataTitle7 { get; set; }
        public Nullable<bool> IsMeta7Searchable { get; set; }
        public Nullable<bool> IsMeta7Required { get; set; }
        public string MetaDataTitle8 { get; set; }
        public Nullable<bool> IsMeta8Searchable { get; set; }
        public Nullable<bool> IsMeta8Required { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChecklistSection> ChecklistSections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChecklistRecord> ChecklistRecords { get; set; }
    }
}
