//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locations_lkup
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string PermissionCode { get; set; }
        public string LocCode { get; set; }
        public string Mall { get; set; }
        public string State { get; set; }
    }
}
